// This file was generated by Rcpp::compileAttributes
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppArmadillo.h>
#include <Rcpp.h>

using namespace Rcpp;

// cont
double cont(arma::vec x, arma::vec y, const arma::vec& w);
RcppExport SEXP wCorr_cont(SEXP xSEXP, SEXP ySEXP, SEXP wSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< arma::vec >::type x(xSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type y(ySEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type w(wSEXP);
    __result = Rcpp::wrap(cont(x, y, w));
    return __result;
END_RCPP
}
// fixxFast
const arma::vec fixxFast(const arma::vec x, const arma::vec w);
RcppExport SEXP wCorr_fixxFast(SEXP xSEXP, SEXP wSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< const arma::vec >::type x(xSEXP);
    Rcpp::traits::input_parameter< const arma::vec >::type w(wSEXP);
    __result = Rcpp::wrap(fixxFast(x, w));
    return __result;
END_RCPP
}
// mapThetaFast
const arma::vec mapThetaFast(const arma::vec& v);
RcppExport SEXP wCorr_mapThetaFast(SEXP vSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< const arma::vec& >::type v(vSEXP);
    __result = Rcpp::wrap(mapThetaFast(v));
    return __result;
END_RCPP
}
// optFcFast
double optFcFast(const arma::vec& par, const arma::vec& x, arma::vec w, const arma::vec& M, double temp3, const arma::vec& theta0);
RcppExport SEXP wCorr_optFcFast(SEXP parSEXP, SEXP xSEXP, SEXP wSEXP, SEXP MSEXP, SEXP temp3SEXP, SEXP theta0SEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< const arma::vec& >::type par(parSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type x(xSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type w(wSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type M(MSEXP);
    Rcpp::traits::input_parameter< double >::type temp3(temp3SEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type theta0(theta0SEXP);
    __result = Rcpp::wrap(optFcFast(par, x, w, M, temp3, theta0));
    return __result;
END_RCPP
}
// optFFast
double optFFast(const arma::vec& par, const arma::vec& x, const arma::vec w, const arma::vec& M, double temp3);
RcppExport SEXP wCorr_optFFast(SEXP parSEXP, SEXP xSEXP, SEXP wSEXP, SEXP MSEXP, SEXP temp3SEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< const arma::vec& >::type par(parSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type x(xSEXP);
    Rcpp::traits::input_parameter< const arma::vec >::type w(wSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type M(MSEXP);
    Rcpp::traits::input_parameter< double >::type temp3(temp3SEXP);
    __result = Rcpp::wrap(optFFast(par, x, w, M, temp3));
    return __result;
END_RCPP
}
// theta
const arma::vec theta(const arma::vec& M);
RcppExport SEXP wCorr_theta(SEXP MSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< const arma::vec& >::type M(MSEXP);
    __result = Rcpp::wrap(theta(M));
    return __result;
END_RCPP
}
// imapThetaFast2
const arma::vec imapThetaFast2(const arma::vec& theta0);
RcppExport SEXP wCorr_imapThetaFast2(SEXP theta0SEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< const arma::vec& >::type theta0(theta0SEXP);
    __result = Rcpp::wrap(imapThetaFast2(theta0));
    return __result;
END_RCPP
}
// mainF
arma::field<arma::vec> mainF(const arma::vec& x, const arma::vec& M, arma::vec w, const arma::vec& theta0);
RcppExport SEXP wCorr_mainF(SEXP xSEXP, SEXP MSEXP, SEXP wSEXP, SEXP theta0SEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< const arma::vec& >::type x(xSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type M(MSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type w(wSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type theta0(theta0SEXP);
    __result = Rcpp::wrap(mainF(x, M, w, theta0));
    return __result;
END_RCPP
}
// imapThetaFast
const arma::vec imapThetaFast(const arma::vec& theta0);
RcppExport SEXP wCorr_imapThetaFast(SEXP theta0SEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< const arma::vec& >::type theta0(theta0SEXP);
    __result = Rcpp::wrap(imapThetaFast(theta0));
    return __result;
END_RCPP
}
// fscale_cutsFast
const arma::vec fscale_cutsFast(const arma::vec& par);
RcppExport SEXP wCorr_fscale_cutsFast(SEXP parSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< const arma::vec& >::type par(parSEXP);
    __result = Rcpp::wrap(fscale_cutsFast(par));
    return __result;
END_RCPP
}
// tableFast
const arma::mat tableFast(const arma::vec& x, const arma::vec& y, const arma::vec& w);
RcppExport SEXP wCorr_tableFast(SEXP xSEXP, SEXP ySEXP, SEXP wSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< const arma::vec& >::type x(xSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type y(ySEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type w(wSEXP);
    __result = Rcpp::wrap(tableFast(x, y, w));
    return __result;
END_RCPP
}
// discord
int discord(const arma::mat& xytab);
RcppExport SEXP wCorr_discord(SEXP xytabSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< const arma::mat& >::type xytab(xytabSEXP);
    __result = Rcpp::wrap(discord(xytab));
    return __result;
END_RCPP
}
// lnlFast
double lnlFast(const arma::mat& xytab, const arma::mat& pm);
RcppExport SEXP wCorr_lnlFast(SEXP xytabSEXP, SEXP pmSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< const arma::mat& >::type xytab(xytabSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type pm(pmSEXP);
    __result = Rcpp::wrap(lnlFast(xytab, pm));
    return __result;
END_RCPP
}
// rcpparma_hello_world
arma::mat rcpparma_hello_world();
RcppExport SEXP wCorr_rcpparma_hello_world() {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    __result = Rcpp::wrap(rcpparma_hello_world());
    return __result;
END_RCPP
}
// rcpparma_outerproduct
arma::mat rcpparma_outerproduct(const arma::colvec& x);
RcppExport SEXP wCorr_rcpparma_outerproduct(SEXP xSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< const arma::colvec& >::type x(xSEXP);
    __result = Rcpp::wrap(rcpparma_outerproduct(x));
    return __result;
END_RCPP
}
// rcpparma_innerproduct
double rcpparma_innerproduct(const arma::colvec& x);
RcppExport SEXP wCorr_rcpparma_innerproduct(SEXP xSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< const arma::colvec& >::type x(xSEXP);
    __result = Rcpp::wrap(rcpparma_innerproduct(x));
    return __result;
END_RCPP
}
// rcpparma_bothproducts
Rcpp::List rcpparma_bothproducts(const arma::colvec& x);
RcppExport SEXP wCorr_rcpparma_bothproducts(SEXP xSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< const arma::colvec& >::type x(xSEXP);
    __result = Rcpp::wrap(rcpparma_bothproducts(x));
    return __result;
END_RCPP
}
