# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

cont <- function(x, y, w) {
    .Call('wCorr_cont', PACKAGE = 'wCorr', x, y, w)
}

fixxFast <- function(x, w) {
    .Call('wCorr_fixxFast', PACKAGE = 'wCorr', x, w)
}

mapThetaFast <- function(v) {
    .Call('wCorr_mapThetaFast', PACKAGE = 'wCorr', v)
}

optFcFast <- function(par, x, w, temp1, temp2, temp3) {
    .Call('wCorr_optFcFast', PACKAGE = 'wCorr', par, x, w, temp1, temp2, temp3)
}

theta <- function(uM, M) {
    .Call('wCorr_theta', PACKAGE = 'wCorr', uM, M)
}

imapThetaFast2 <- function(theta0) {
    .Call('wCorr_imapThetaFast2', PACKAGE = 'wCorr', theta0)
}

mainF <- function(x, M, w) {
    .Call('wCorr_mainF', PACKAGE = 'wCorr', x, M, w)
}

imapThetaFast <- function(theta0) {
    .Call('wCorr_imapThetaFast', PACKAGE = 'wCorr', theta0)
}

fscale_cutsFast <- function(par) {
    .Call('wCorr_fscale_cutsFast', PACKAGE = 'wCorr', par)
}

tableFast <- function(x, y, w) {
    .Call('wCorr_tableFast', PACKAGE = 'wCorr', x, y, w)
}

discord <- function(xytab) {
    .Call('wCorr_discord', PACKAGE = 'wCorr', xytab)
}

lnlFast <- function(xytab, pm) {
    .Call('wCorr_lnlFast', PACKAGE = 'wCorr', xytab, pm)
}

