# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

cont <- function(x, y, w) {
    .Call('wCorr_cont', PACKAGE = 'wCorr', x, y, w)
}

fixxFast <- function(x, w) {
    .Call('wCorr_fixxFast', PACKAGE = 'wCorr', x, w)
}

mapThetaFast <- function(v) {
    .Call('wCorr_mapThetaFast', PACKAGE = 'wCorr', v)
}

optFcFast <- function(par, x, w, M, temp3, theta0) {
    .Call('wCorr_optFcFast', PACKAGE = 'wCorr', par, x, w, M, temp3, theta0)
}

optFFast <- function(par, x, w, M, temp3) {
    .Call('wCorr_optFFast', PACKAGE = 'wCorr', par, x, w, M, temp3)
}

theta <- function(M) {
    .Call('wCorr_theta', PACKAGE = 'wCorr', M)
}

imapThetaFast2 <- function(theta0) {
    .Call('wCorr_imapThetaFast2', PACKAGE = 'wCorr', theta0)
}

mainF <- function(x, M, w, theta0) {
    .Call('wCorr_mainF', PACKAGE = 'wCorr', x, M, w, theta0)
}

imapThetaFast <- function(theta0) {
    .Call('wCorr_imapThetaFast', PACKAGE = 'wCorr', theta0)
}

fscale_cutsFast <- function(par) {
    .Call('wCorr_fscale_cutsFast', PACKAGE = 'wCorr', par)
}

tableFast <- function(x, y, w) {
    .Call('wCorr_tableFast', PACKAGE = 'wCorr', x, y, w)
}

discord <- function(xytab) {
    .Call('wCorr_discord', PACKAGE = 'wCorr', xytab)
}

lnlFast <- function(xytab, pm) {
    .Call('wCorr_lnlFast', PACKAGE = 'wCorr', xytab, pm)
}

rcpparma_hello_world <- function() {
    .Call('wCorr_rcpparma_hello_world', PACKAGE = 'wCorr')
}

rcpparma_outerproduct <- function(x) {
    .Call('wCorr_rcpparma_outerproduct', PACKAGE = 'wCorr', x)
}

rcpparma_innerproduct <- function(x) {
    .Call('wCorr_rcpparma_innerproduct', PACKAGE = 'wCorr', x)
}

rcpparma_bothproducts <- function(x) {
    .Call('wCorr_rcpparma_bothproducts', PACKAGE = 'wCorr', x)
}

